name: wizard-mongos-expres-io

networks:
  master-netwrk:
    external: true

services:
  wizard-mongos-expres-io:
    container_name: ${APP_NAME}_mongos-expres-io
    build:
      context: .
      dockerfile: Dockerfile
    env_file: ../../.env
    ports:
      - ${MONGOS_EXPRES_IO_PORT}:${MONGOS_EXPRES_IO_PORT_OF}
    restart: always
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_ADMINIST_SHARDE_MATTER}:${MONGO_PASSWORD_SHARDE_MATTER}@${MONGOS_ROUTER_DN_ADRS}:${MONGOS_ROUTER_DN_PORT_OF},${MONGOS_ROUTER_HN_ADRS}:${MONGOS_ROUTER_HN_PORT_OF},${MONGOS_ROUTER_SG_ADRS}:${MONGOS_ROUTER_SG_PORT_OF}/admin?authSource=admin
      ME_CONFIG_BASICAUTH_USERNAME: ${EXPRESS_ADMINIST}
      ME_CONFIG_BASICAUTH_PASSWORD: ${EXPRESS_PASSWORD}
      PORT: ${MONGOS_EXPRES_IO_PORT_OF}
    networks:
      - master-netwrk
