# =====================================================
# DOCKER COMPOSE - MONGODB SHARDED CLUSTER
# =====================================================
# Stack:
# - Config Servers (configRS)
# - Shardes: everesRS / fansipRS / fujimoRS
# - Router: mongos-router-dn / mongos-router-hn / mongos-router-sg
# - UI: mongo-express
# =====================================================

version: "3.9"

networks:
  nest-cluster:
    external: true

services:
  keygen:
    container_name: ${APP_NAME}_keygen
    image: mongo:7
    volumes:
      - ./keyfile:/keyfile
      - ./keygen:/keygen
      - /var/run/docker.sock:/var/run/docker.sock
    entrypoint: ["bash", "/keygen/create-keyfile.sh"]
    networks:
      - nest-cluster

  mongos-router-dn:
    container_name: ${APP_NAME}_mongos-router-dn
    image: mongo:7
    volumes:
        - ./keyfile:/etc
        - ./init/init-config-server.js:/init/init-config-server.js:ro
        - ./init/init-sharde-everes.js:/init/init-sharde-everes.js:ro
        - ./init/init-sharde-fansip.js:/init/init-sharde-fansip.js:ro
        - ./init/init-sharde-fujimo.js:/init/init-sharde-fujimo.js:ro
        # - ./data/config-sv/config-sv-primary:/data/db
    env_file: .env
    networks:
      - nest-cluster
    command: |
      bash -c "
        while [ ! -f /etc/mongo-keyfile ]; do
          echo 'WAITING FOR KEYFILE...'
          sleep 5
        done

        mkdir -p /data/config-server
        mkdir -p /data/sharde-everes
        mkdir -p /data/sharde-fansip
        mkdir -p /data/sharde-fujimo

        mongod --replSet configRS --bind_ip_all --configsvr --port 27018 --dbpath /data/config-server --fork --logpath /tmp/mongod.log
        mongod --replSet everesRS --bind_ip_all --shardsvr --port 27019 --dbpath /data/sharde-everes --fork --logpath /tmp/mongod.log
        mongod --replSet fansipRS --bind_ip_all --shardsvr --port 27020 --dbpath /data/sharde-fansip --fork --logpath /tmp/mongod.log
        mongod --replSet fujimoRS --bind_ip_all --shardsvr --port 27021 --dbpath /data/sharde-fujimo --fork --logpath /tmp/mongod.log

        echo 'WAITING FOR sharde-everes-dn'
        until mongosh --quiet --host mongos-router-dn:27019 --eval 'db.adminCommand({ ping: 1 })' > /dev/null 2>&1; do
          sleep 2
        done
        echo 'sharde-everes-dn READY'

        echo 'WAITING FOR sharde-fansip-dn'
        until mongosh --quiet --host mongos-router-dn:27020 --eval 'db.adminCommand({ ping: 1 })' > /dev/null 2>&1; do
          sleep 2
        done
        echo 'sharde-fansip-dn READY'

        echo 'WAITING FOR sharde-fujimo-dn'
        until mongosh --quiet --host mongos-router-dn:27021 --eval 'db.adminCommand({ ping: 1 })' > /dev/null 2>&1; do
          sleep 2
        done
        echo 'sharde-fujimo-dn READY'

        echo 'WAITING FOR sharde-everes-hn'
        until mongosh --quiet --host mongos-router-hn:27019 --eval 'db.adminCommand({ ping: 1 })' > /dev/null 2>&1; do
          sleep 2
        done
        echo 'sharde-everes-hn READY'

        echo 'WAITING FOR sharde-fansip-hn'
        until mongosh --quiet --host mongos-router-hn:27020 --eval 'db.adminCommand({ ping: 1 })' > /dev/null 2>&1; do
          sleep 2
        done
        echo 'sharde-fansip-hn READY'

        echo 'WAITING FOR sharde-fujimo-hn'
        until mongosh --quiet --host mongos-router-hn:27021 --eval 'db.adminCommand({ ping: 1 })' > /dev/null 2>&1; do
          sleep 2
        done
        echo 'sharde-fujimo-hn READY'

        echo 'WAITING FOR sharde-everes-sg'
        until mongosh --quiet --host mongos-router-sg:27019 --eval 'db.adminCommand({ ping: 1 })' > /dev/null 2>&1; do
          sleep 2
        done
        echo 'sharde-everes-sg READY'

        echo 'WAITING FOR sharde-fansip-sg'
        until mongosh --quiet --host mongos-router-sg:27020 --eval 'db.adminCommand({ ping: 1 })' > /dev/null 2>&1; do
          sleep 2
        done
        echo 'sharde-fansip-sg READY'

        echo 'WAITING FOR sharde-fujimo-sg'
        until mongosh --quiet --host mongos-router-sg:27021 --eval 'db.adminCommand({ ping: 1 })' > /dev/null 2>&1; do
          sleep 2
        done
        echo 'sharde-fujimo-sg READY'

        mongosh --host mongos-router-dn:27018 /init/init-config-server.js
        mongosh --host mongos-router-dn:27019 /init/init-sharde-everes.js
        mongosh --host mongos-router-dn:27020 /init/init-sharde-fansip.js
        mongosh --host mongos-router-dn:27021 /init/init-sharde-fujimo.js

        tail -f /dev/null
      "

  mongos-router-hn:
    container_name: ${APP_NAME}_mongos-router-hn
    image: mongo:7
    volumes:
        - ./keyfile:/etc
        # - ./data/config-sv/config-sv-primary:/data/db
    env_file: .env
    networks:
      - nest-cluster
    command: |
      bash -c "
        while [ ! -f /etc/mongo-keyfile ]; do
          echo 'WAITING FOR KEYFILE...'
          sleep 5
        done

        mkdir -p /data/config-server
        mkdir -p /data/sharde-everes
        mkdir -p /data/sharde-fansip
        mkdir -p /data/sharde-fujimo

        mongod --replSet configRS --bind_ip_all --configsvr --port 27018 --dbpath /data/config-server --fork --logpath /tmp/mongod.log
        mongod --replSet everesRS --bind_ip_all --shardsvr --port 27019 --dbpath /data/sharde-everes --fork --logpath /tmp/mongod.log
        mongod --replSet fansipRS --bind_ip_all --shardsvr --port 27020 --dbpath /data/sharde-fansip --fork --logpath /tmp/mongod.log
        mongod --replSet fujimoRS --bind_ip_all --shardsvr --port 27021 --dbpath /data/sharde-fujimo --fork --logpath /tmp/mongod.log

        tail -f /dev/null
      "

  mongos-router-sg:
    container_name: ${APP_NAME}_mongos-router-sg
    image: mongo:7
    volumes:
        - ./keyfile:/etc
        # - ./data/config-sv/config-sv-primary:/data/db
    env_file: .env
    networks:
      - nest-cluster
    command: |
      bash -c "
        while [ ! -f /etc/mongo-keyfile ]; do
          echo 'WAITING FOR KEYFILE...'
          sleep 5
        done

        mkdir -p /data/config-server
        mkdir -p /data/sharde-everes
        mkdir -p /data/sharde-fansip
        mkdir -p /data/sharde-fujimo

        mongod --replSet configRS --bind_ip_all --configsvr --port 27018 --dbpath /data/config-server --fork --logpath /tmp/mongod.log
        mongod --replSet everesRS --bind_ip_all --shardsvr --port 27019 --dbpath /data/sharde-everes --fork --logpath /tmp/mongod.log
        mongod --replSet fansipRS --bind_ip_all --shardsvr --port 27020 --dbpath /data/sharde-fansip --fork --logpath /tmp/mongod.log
        mongod --replSet fujimoRS --bind_ip_all --shardsvr --port 27021 --dbpath /data/sharde-fujimo --fork --logpath /tmp/mongod.log

        tail -f /dev/null
      "
