name: mongos-router-sg

networks:
  master-netwrk:
    external: true

services:
  mongos-router-sg:
    container_name: ${APP_NAME}_mongos-router-sg
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./keyfile:/etc
      - mongos-router-sg-da:/data/db
      - mongos-router-sg-cf:/data/configdb
    env_file: ../../.env
    ports:
      - ${MONGOS_ROUTER_SG_PORT}:${MONGOS_ROUTER_SG_PORT_OF}
    networks:
      - master-netwrk

volumes:
  mongos-router-sg-da:
  mongos-router-sg-cf:
