name: wizard-sharde-fujimo-dn

networks:
  master-netwrk:
    external: true

services:
  wizard-sharde-fujimo-dn:
    container_name: ${APP_NAME}_sharde-fujimo-dn
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./keyfile:/etc
      - wizard-sharde-fujimo-dn-da:/data/db
      - wizard-sharde-fujimo-dn-cf:/data/configdb
      - ./init/init-sharde-fujimo.js:/init/init-sharde-fujimo.js:ro
    env_file: ../../.env
    ports:
      - ${SHARDE_FUJIMO_DN_PORT}:${SHARDE_FUJIMO_DN_PORT_OF}
    networks:
      - master-netwrk

volumes:
  wizard-sharde-fujimo-dn-da:
  wizard-sharde-fujimo-dn-cf:
