name: mongos-master

x-mongo-image: &mongo-image mongo:7.0.14@sha256:0032d2ca20db5fa34926f196c8a43b74e34ed239a7f2453ff1505b6f12ba8ea6

networks:
  master-netwrk:
    external: true

services:
  sharde-everes-dn:
    container_name: ${APP_NAME}_sharde-everes-dn
    image: *mongo-image
    volumes:
      - ./keyfile:/etc
      - sharde-everes-dn-da:/data/db
      - sharde-everes-dn-cf:/data/configdb
      - ./init/init-sharde-everes.js:/init/init-sharde-everes.js:ro
    env_file: ../.env
    ports:
      - ${SHARDE_EVERES_DN_PORT}:${SHARDE_EVERES_DN_PORT_OF}
    networks:
      - master-netwrk
    command: |
      bash -c "
        set -e

        echo 'WAITING FOR KEYFILE...'
        while [ ! -f /etc/mongo-keyfile ]; do sleep 2; done
        echo 'KEYFILE CREATED'

        mkdir -p /data/db

        echo 'STARTING UP SHARDE-EVERES-DN IN PROGRESS WITH NO AUTH'
        mongod --replSet everesRS --bind_ip_all --port ${SHARDE_EVERES_DN_PORT_OF} --dbpath /data/db --fork --logpath /tmp/mongod.log --shardsvr
        echo 'THE SHARDE-EVERES-DN HAVE FINISHED BOOTING UP WITH NO AUTH'

        echo 'WAITING FOR SHARDE-EVERES-HN'
        until mongosh --quiet --host ${SHARDE_EVERES_HN_ADRS}:${SHARDE_EVERES_HN_PORT_OF} --eval 'db.adminCommand({ ping: 1 })' > /dev/null 2>&1; do sleep 2; done
        echo 'SHARDE-EVERES-HN READY'

        echo 'WAITING FOR SHARDE-EVERES-SG'
        until mongosh --quiet --host ${SHARDE_EVERES_SG_ADRS}:${SHARDE_EVERES_SG_PORT_OF} --eval 'db.adminCommand({ ping: 1 })' > /dev/null 2>&1; do sleep 2; done
        echo 'SHARDE-EVERES-SG READY'

        echo 'WAITING SHARDE-EVERES-DN FOR INIT'
        mongosh --host ${SHARDE_EVERES_DN_ADRS}:${SHARDE_EVERES_DN_PORT_OF} /init/init-sharde-everes.js
        echo 'SHARDE-EVERES-DN INIT DONE'

        echo 'WAITING FOR STARTING UP SHARDE-EVERES-DN IN PROGRESS WITH AUTH'
        mongod --shutdown --dbpath /data/db
        while pgrep mongod >/dev/null; do sleep 2; done
        mongod --replSet everesRS --bind_ip_all --port ${SHARDE_EVERES_DN_PORT_OF} --dbpath /data/db --auth --keyFile /etc/mongo-keyfile --setParameter enableLocalhostAuthBypass=0 --fork --logpath /tmp/mongod.log --shardsvr
        until mongosh --quiet --host ${SHARDE_EVERES_DN_ADRS}:${SHARDE_EVERES_DN_PORT_OF} --eval 'db.adminCommand({ ping: 1 })' > /dev/null 2>&1; do sleep 2; done
        echo 'THE SHARDE-EVERES-DN HAVE FINISHED BOOTING UP WITH AUTH'

        tail -f /tmp/mongod.log
      "

volumes:
  sharde-everes-dn-da:
  sharde-everes-dn-cf:
