name: devlop-router-io

x-mongo-image: &mongo-image mongo:7.0.14@sha256:0032d2ca20db5fa34926f196c8a43b74e34ed239a7f2453ff1505b6f12ba8ea6
x-mongo-express-image: &mongo-express-image mongo-express:1.0.2@sha256:1b23d7976f0210dbec74045c209e52fbb26d29b2e873d6c6fa3d3f0ae32c2a64

networks:
  master-netwrk:
    external: true

services:
  devlop-router-ms:
    container_name: ${APP_NAME}_devlop-router-ms
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./keyfile:/etc
      - devlop-router-ms-da:/data/db
      - devlop-router-ms-cf:/data/configdb
      - ../sharde-everes-dn/init/init-sharde-everes.js:/init/init-sharde-everes.js:ro
      - ../sharde-fansip-dn/init/init-sharde-fansip.js:/init/init-sharde-fansip.js:ro
      - ../sharde-fujimo-dn/init/init-sharde-fujimo.js:/init/init-sharde-fujimo.js:ro
      - ../sharde-matter-dn/init/init-sharde-matter.js:/init/init-sharde-matter.js:ro
      - ../mongos-router-dn/init/cluster.js:/init/cluster.js:ro
    env_file: ../../.env
    ports:
      - ${SHARDE_EVERES_DN_PORT}:${SHARDE_EVERES_DN_PORT_OF}
      - ${SHARDE_EVERES_HN_PORT}:${SHARDE_EVERES_HN_PORT_OF}
      - ${SHARDE_EVERES_SG_PORT}:${SHARDE_EVERES_SG_PORT_OF}
      - ${SHARDE_FANSIP_DN_PORT}:${SHARDE_FANSIP_DN_PORT_OF}
      - ${SHARDE_FANSIP_HN_PORT}:${SHARDE_FANSIP_HN_PORT_OF}
      - ${SHARDE_FANSIP_SG_PORT}:${SHARDE_FANSIP_SG_PORT_OF}
      - ${SHARDE_FUJIMO_DN_PORT}:${SHARDE_FUJIMO_DN_PORT_OF}
      - ${SHARDE_FUJIMO_HN_PORT}:${SHARDE_FUJIMO_HN_PORT_OF}
      - ${SHARDE_FUJIMO_SG_PORT}:${SHARDE_FUJIMO_SG_PORT_OF}
      - ${SHARDE_MATTER_DN_PORT}:${SHARDE_MATTER_DN_PORT_OF}
      - ${SHARDE_MATTER_HN_PORT}:${SHARDE_MATTER_HN_PORT_OF}
      - ${SHARDE_MATTER_SG_PORT}:${SHARDE_MATTER_SG_PORT_OF}
      - ${MONGOS_ROUTER_DN_PORT}:${MONGOS_ROUTER_DN_PORT_OF}
      - ${MONGOS_ROUTER_HN_PORT}:${MONGOS_ROUTER_HN_PORT_OF}
      - ${MONGOS_ROUTER_SG_PORT}:${MONGOS_ROUTER_SG_PORT_OF}
    networks:
      - master-netwrk

volumes:
  devlop-router-ms-da:
  devlop-router-ms-cf:
