name: devlop-router-io

x-mongo-image: &mongo-image mongo:7.0.14@sha256:0032d2ca20db5fa34926f196c8a43b74e34ed239a7f2453ff1505b6f12ba8ea6
x-mongo-express-image: &mongo-express-image mongo-express:1.0.2@sha256:1b23d7976f0210dbec74045c209e52fbb26d29b2e873d6c6fa3d3f0ae32c2a64

networks:
  master-netwrk:
    external: true

services:
  devlop-router-ms:
    container_name: ${APP_NAME}_devlop-router-ms
    image: *mongo-image
    volumes:
      - ./keyfile:/etc
      - devlop-router-ms-da:/data/db
      - devlop-router-ms-cf:/data/configdb
      - ../sharde-everes-dn/init/init-sharde-everes.js:/init/init-sharde-everes.js:ro
      - ../sharde-fansip-dn/init/init-sharde-fansip.js:/init/init-sharde-fansip.js:ro
      - ../sharde-fujimo-dn/init/init-sharde-fujimo.js:/init/init-sharde-fujimo.js:ro
      - ../sharde-matter-dn/init/init-sharde-matter.js:/init/init-sharde-matter.js:ro
      - ../mongos-router-dn/init/cluster.js:/init/cluster.js:ro
    env_file: ../../.env
    ports:
      - ${SHARDE_EVERES_DN_PORT}:${SHARDE_EVERES_DN_PORT_OF}
      - ${SHARDE_EVERES_HN_PORT}:${SHARDE_EVERES_HN_PORT_OF}
      - ${SHARDE_EVERES_SG_PORT}:${SHARDE_EVERES_SG_PORT_OF}
      - ${SHARDE_FANSIP_DN_PORT}:${SHARDE_FANSIP_DN_PORT_OF}
      - ${SHARDE_FANSIP_HN_PORT}:${SHARDE_FANSIP_HN_PORT_OF}
      - ${SHARDE_FANSIP_SG_PORT}:${SHARDE_FANSIP_SG_PORT_OF}
      - ${SHARDE_FUJIMO_DN_PORT}:${SHARDE_FUJIMO_DN_PORT_OF}
      - ${SHARDE_FUJIMO_HN_PORT}:${SHARDE_FUJIMO_HN_PORT_OF}
      - ${SHARDE_FUJIMO_SG_PORT}:${SHARDE_FUJIMO_SG_PORT_OF}
      - ${SHARDE_MATTER_DN_PORT}:${SHARDE_MATTER_DN_PORT_OF}
      - ${SHARDE_MATTER_HN_PORT}:${SHARDE_MATTER_HN_PORT_OF}
      - ${SHARDE_MATTER_SG_PORT}:${SHARDE_MATTER_SG_PORT_OF}
      - ${MONGOS_ROUTER_DN_PORT}:${MONGOS_ROUTER_DN_PORT_OF}
      - ${MONGOS_ROUTER_HN_PORT}:${MONGOS_ROUTER_HN_PORT_OF}
      - ${MONGOS_ROUTER_SG_PORT}:${MONGOS_ROUTER_SG_PORT_OF}
    networks:
      - master-netwrk
    command: |
      bash -c "
        set -e

        echo 'WAITING FOR KEYFILE...'
        while [ ! -f /etc/mongo-keyfile ]; do sleep 2; done
        echo 'KEYFILE CREATED'

        # ------------------------------------------------------------------------- SHARDE_EVERES HEAD
        mkdir -p /data/db/SHARDE_EVERES_DN
        mkdir -p /data/db/SHARDE_EVERES_HN
        mkdir -p /data/db/SHARDE_EVERES_SG
        mkdir -p /tmp/SHARDE_EVERES_DN
        mkdir -p /tmp/SHARDE_EVERES_HN
        mkdir -p /tmp/SHARDE_EVERES_SG

        echo 'STARTING UP SHARDE-EVERES-DN IN PROGRESS WITH NO AUTH'
        mongod --replSet everesRS --bind_ip_all --port ${SHARDE_EVERES_DN_PORT_OF} --dbpath /data/db/SHARDE_EVERES_DN --fork --logpath /tmp/SHARDE_EVERES_DN/mongod.log --shardsvr
        echo 'THE SHARDE-EVERES-DN HAVE FINISHED BOOTING UP WITH NO AUTH'

        echo 'STARTING UP SHARDE-EVERES-HN IN PROGRESS WITH NO AUTH'
        mongod --replSet everesRS --bind_ip_all --port ${SHARDE_EVERES_HN_PORT_OF} --dbpath /data/db/SHARDE_EVERES_HN --fork --logpath /tmp/SHARDE_EVERES_HN/mongod.log --shardsvr
        echo 'THE SHARDE-EVERES-HN HAVE FINISHED BOOTING UP WITH NO AUTH'

        echo 'STARTING UP SHARDE-EVERES-SG IN PROGRESS WITH NO AUTH'
        mongod --replSet everesRS --bind_ip_all --port ${SHARDE_EVERES_SG_PORT_OF} --dbpath /data/db/SHARDE_EVERES_SG --fork --logpath /tmp/SHARDE_EVERES_SG/mongod.log --shardsvr
        echo 'THE SHARDE-EVERES-SG HAVE FINISHED BOOTING UP WITH NO AUTH'

        echo 'WAITING SHARDE-EVERES-DN FOR INIT'
        mongosh --host ${SHARDE_EVERES_DN_ADRS}:${SHARDE_EVERES_DN_PORT_OF} /init/init-sharde-everes.js
        echo 'SHARDE-EVERES-DN INIT DONE'

        echo 'WAITING FOR STARTING UP SHARDE-EVERES-DN IN PROGRESS WITH AUTH'
        mongod --shutdown --dbpath /data/db/SHARDE_EVERES_DN
        until ! mongosh --quiet --host ${SHARDE_EVERES_DN_ADRS}:${SHARDE_EVERES_DN_PORT_OF} --eval 'db.adminCommand({ ping: 1 })' >/dev/null 2>&1; do sleep 2; done
        mongod --replSet everesRS --bind_ip_all --port ${SHARDE_EVERES_DN_PORT_OF} --dbpath /data/db/SHARDE_EVERES_DN --auth --keyFile /etc/mongo-keyfile --setParameter enableLocalhostAuthBypass=0 --fork --logpath /tmp/SHARDE_EVERES_DN/mongod.log --shardsvr
        until mongosh --quiet --host ${SHARDE_EVERES_DN_ADRS}:${SHARDE_EVERES_DN_PORT_OF} --eval 'db.adminCommand({ ping: 1 })' > /dev/null 2>&1; do sleep 2; done
        echo 'THE SHARDE-EVERES-DN HAVE FINISHED BOOTING UP WITH AUTH'

        echo 'WAITING FOR STARTING UP SHARDE-EVERES-HN IN PROGRESS WITH AUTH'
        mongod --shutdown --dbpath /data/db/SHARDE_EVERES_HN
        until ! mongosh --quiet --host ${SHARDE_EVERES_HN_ADRS}:${SHARDE_EVERES_HN_PORT_OF} --eval 'db.adminCommand({ ping: 1 })' >/dev/null 2>&1; do sleep 2; done
        mongod --replSet everesRS --bind_ip_all --port ${SHARDE_EVERES_HN_PORT_OF} --dbpath /data/db/SHARDE_EVERES_HN --auth --keyFile /etc/mongo-keyfile --setParameter enableLocalhostAuthBypass=0 --fork --logpath /tmp/SHARDE_EVERES_HN/mongod.log --shardsvr
        until mongosh --quiet --host ${SHARDE_EVERES_HN_ADRS}:${SHARDE_EVERES_HN_PORT_OF} --eval 'db.adminCommand({ ping: 1 })' > /dev/null 2>&1; do sleep 2; done
        echo 'THE SHARDE-EVERES-HN HAVE FINISHED BOOTING UP WITH AUTH'

        echo 'WAITING FOR STARTING UP SHARDE-EVERES-SG IN PROGRESS WITH AUTH'
        mongod --shutdown --dbpath /data/db/SHARDE_EVERES_SG
        until ! mongosh --quiet --host ${SHARDE_EVERES_SG_ADRS}:${SHARDE_EVERES_SG_PORT_OF} --eval 'db.adminCommand({ ping: 1 })' >/dev/null 2>&1; do sleep 2; done
        mongod --replSet everesRS --bind_ip_all --port ${SHARDE_EVERES_SG_PORT_OF} --dbpath /data/db/SHARDE_EVERES_SG --auth --keyFile /etc/mongo-keyfile --setParameter enableLocalhostAuthBypass=0 --fork --logpath /tmp/SHARDE_EVERES_SG/mongod.log --shardsvr
        until mongosh --quiet --host ${SHARDE_EVERES_SG_ADRS}:${SHARDE_EVERES_SG_PORT_OF} --eval 'db.adminCommand({ ping: 1 })' > /dev/null 2>&1; do sleep 2; done
        echo 'THE SHARDE-EVERES-SG HAVE FINISHED BOOTING UP WITH AUTH'
        # ------------------------------------------------------------------------- SHARDE_EVERES TAIL

        # ------------------------------------------------------------------------- SHARDE_FANSIP HEAD
        mkdir -p /data/db/SHARDE_FANSIP_DN
        mkdir -p /data/db/SHARDE_FANSIP_HN
        mkdir -p /data/db/SHARDE_FANSIP_SG
        mkdir -p /tmp/SHARDE_FANSIP_DN
        mkdir -p /tmp/SHARDE_FANSIP_HN
        mkdir -p /tmp/SHARDE_FANSIP_SG

        echo 'STARTING UP SHARDE-FANSIP-DN IN PROGRESS WITH NO AUTH'
        mongod --replSet fansipRS --bind_ip_all --port ${SHARDE_FANSIP_DN_PORT_OF} --dbpath /data/db/SHARDE_FANSIP_DN --fork --logpath /tmp/SHARDE_FANSIP_DN/mongod.log --shardsvr
        echo 'THE SHARDE-FANSIP-DN HAVE FINISHED BOOTING UP WITH NO AUTH'

        echo 'STARTING UP SHARDE-FANSIP-HN IN PROGRESS WITH NO AUTH'
        mongod --replSet fansipRS --bind_ip_all --port ${SHARDE_FANSIP_HN_PORT_OF} --dbpath /data/db/SHARDE_FANSIP_HN --fork --logpath /tmp/SHARDE_FANSIP_HN/mongod.log --shardsvr
        echo 'THE SHARDE-FANSIP-HN HAVE FINISHED BOOTING UP WITH NO AUTH'

        echo 'STARTING UP SHARDE-FANSIP-SG IN PROGRESS WITH NO AUTH'
        mongod --replSet fansipRS --bind_ip_all --port ${SHARDE_FANSIP_SG_PORT_OF} --dbpath /data/db/SHARDE_FANSIP_SG --fork --logpath /tmp/SHARDE_FANSIP_SG/mongod.log --shardsvr
        echo 'THE SHARDE-FANSIP-SG HAVE FINISHED BOOTING UP WITH NO AUTH'

        echo 'WAITING SHARDE-FANSIP-DN FOR INIT'
        mongosh --host ${SHARDE_FANSIP_DN_ADRS}:${SHARDE_FANSIP_DN_PORT_OF} /init/init-sharde-fansip.js
        echo 'SHARDE-FANSIP-DN INIT DONE'

        echo 'WAITING FOR STARTING UP SHARDE-FANSIP-DN IN PROGRESS WITH AUTH'
        mongod --shutdown --dbpath /data/db/SHARDE_FANSIP_DN
        until ! mongosh --quiet --host ${SHARDE_FANSIP_DN_ADRS}:${SHARDE_FANSIP_DN_PORT_OF} --eval 'db.adminCommand({ ping: 1 })' >/dev/null 2>&1; do sleep 2; done
        mongod --replSet fansipRS --bind_ip_all --port ${SHARDE_FANSIP_DN_PORT_OF} --dbpath /data/db/SHARDE_FANSIP_DN --auth --keyFile /etc/mongo-keyfile --setParameter enableLocalhostAuthBypass=0 --fork --logpath /tmp/SHARDE_FANSIP_DN/mongod.log --shardsvr
        until mongosh --quiet --host ${SHARDE_FANSIP_DN_ADRS}:${SHARDE_FANSIP_DN_PORT_OF} --eval 'db.adminCommand({ ping: 1 })' > /dev/null 2>&1; do sleep 2; done
        echo 'THE SHARDE-FANSIP-DN HAVE FINISHED BOOTING UP WITH AUTH'

        echo 'WAITING FOR STARTING UP SHARDE-FANSIP-HN IN PROGRESS WITH AUTH'
        mongod --shutdown --dbpath /data/db/SHARDE_FANSIP_HN
        until ! mongosh --quiet --host ${SHARDE_FANSIP_HN_ADRS}:${SHARDE_FANSIP_HN_PORT_OF} --eval 'db.adminCommand({ ping: 1 })' >/dev/null 2>&1; do sleep 2; done
        mongod --replSet fansipRS --bind_ip_all --port ${SHARDE_FANSIP_HN_PORT_OF} --dbpath /data/db/SHARDE_FANSIP_HN --auth --keyFile /etc/mongo-keyfile --setParameter enableLocalhostAuthBypass=0 --fork --logpath /tmp/SHARDE_FANSIP_HN/mongod.log --shardsvr
        until mongosh --quiet --host ${SHARDE_FANSIP_HN_ADRS}:${SHARDE_FANSIP_HN_PORT_OF} --eval 'db.adminCommand({ ping: 1 })' > /dev/null 2>&1; do sleep 2; done
        echo 'THE SHARDE-FANSIP-HN HAVE FINISHED BOOTING UP WITH AUTH'

        echo 'WAITING FOR STARTING UP SHARDE-FANSIP-SG IN PROGRESS WITH AUTH'
        mongod --shutdown --dbpath /data/db/SHARDE_FANSIP_SG
        until ! mongosh --quiet --host ${SHARDE_FANSIP_SG_ADRS}:${SHARDE_FANSIP_SG_PORT_OF} --eval 'db.adminCommand({ ping: 1 })' >/dev/null 2>&1; do sleep 2; done
        mongod --replSet fansipRS --bind_ip_all --port ${SHARDE_FANSIP_SG_PORT_OF} --dbpath /data/db/SHARDE_FANSIP_SG --auth --keyFile /etc/mongo-keyfile --setParameter enableLocalhostAuthBypass=0 --fork --logpath /tmp/SHARDE_FANSIP_SG/mongod.log --shardsvr
        until mongosh --quiet --host ${SHARDE_FANSIP_SG_ADRS}:${SHARDE_FANSIP_SG_PORT_OF} --eval 'db.adminCommand({ ping: 1 })' > /dev/null 2>&1; do sleep 2; done
        echo 'THE SHARDE-FANSIP-SG HAVE FINISHED BOOTING UP WITH AUTH'
        # ------------------------------------------------------------------------- SHARDE_FANSIP TAIL

        # ------------------------------------------------------------------------- SHARDE_FUJIMO HEAD
        mkdir -p /data/db/SHARDE_FUJIMO_DN
        mkdir -p /data/db/SHARDE_FUJIMO_HN
        mkdir -p /data/db/SHARDE_FUJIMO_SG
        mkdir -p /tmp/SHARDE_FUJIMO_DN
        mkdir -p /tmp/SHARDE_FUJIMO_HN
        mkdir -p /tmp/SHARDE_FUJIMO_SG

        echo 'STARTING UP SHARDE-FUJIMO-DN IN PROGRESS WITH NO AUTH'
        mongod --replSet fujimoRS --bind_ip_all --port ${SHARDE_FUJIMO_DN_PORT_OF} --dbpath /data/db/SHARDE_FUJIMO_DN --fork --logpath /tmp/SHARDE_FUJIMO_DN/mongod.log --shardsvr
        echo 'THE SHARDE-FUJIMO-DN HAVE FINISHED BOOTING UP WITH NO AUTH'

        echo 'STARTING UP SHARDE-FUJIMO-HN IN PROGRESS WITH NO AUTH'
        mongod --replSet fujimoRS --bind_ip_all --port ${SHARDE_FUJIMO_HN_PORT_OF} --dbpath /data/db/SHARDE_FUJIMO_HN --fork --logpath /tmp/SHARDE_FUJIMO_HN/mongod.log --shardsvr
        echo 'THE SHARDE-FUJIMO-HN HAVE FINISHED BOOTING UP WITH NO AUTH'

        echo 'STARTING UP SHARDE-FUJIMO-SG IN PROGRESS WITH NO AUTH'
        mongod --replSet fujimoRS --bind_ip_all --port ${SHARDE_FUJIMO_SG_PORT_OF} --dbpath /data/db/SHARDE_FUJIMO_SG --fork --logpath /tmp/SHARDE_FUJIMO_SG/mongod.log --shardsvr
        echo 'THE SHARDE-FUJIMO-SG HAVE FINISHED BOOTING UP WITH NO AUTH'

        echo 'WAITING SHARDE-FUJIMO-DN FOR INIT'
        mongosh --host ${SHARDE_FUJIMO_DN_ADRS}:${SHARDE_FUJIMO_DN_PORT_OF} /init/init-sharde-fujimo.js
        echo 'SHARDE-FUJIMO-DN INIT DONE'

        echo 'WAITING FOR STARTING UP SHARDE-FUJIMO-DN IN PROGRESS WITH AUTH'
        mongod --shutdown --dbpath /data/db/SHARDE_FUJIMO_DN
        until ! mongosh --quiet --host ${SHARDE_FUJIMO_DN_ADRS}:${SHARDE_FUJIMO_DN_PORT_OF} --eval 'db.adminCommand({ ping: 1 })' >/dev/null 2>&1; do sleep 2; done
        mongod --replSet fujimoRS --bind_ip_all --port ${SHARDE_FUJIMO_DN_PORT_OF} --dbpath /data/db/SHARDE_FUJIMO_DN --auth --keyFile /etc/mongo-keyfile --setParameter enableLocalhostAuthBypass=0 --fork --logpath /tmp/SHARDE_FUJIMO_DN/mongod.log --shardsvr
        until mongosh --quiet --host ${SHARDE_FUJIMO_DN_ADRS}:${SHARDE_FUJIMO_DN_PORT_OF} --eval 'db.adminCommand({ ping: 1 })' > /dev/null 2>&1; do sleep 2; done
        echo 'THE SHARDE-FUJIMO-DN HAVE FINISHED BOOTING UP WITH AUTH'

        echo 'WAITING FOR STARTING UP SHARDE-FUJIMO-HN IN PROGRESS WITH AUTH'
        mongod --shutdown --dbpath /data/db/SHARDE_FUJIMO_HN
        until ! mongosh --quiet --host ${SHARDE_FUJIMO_HN_ADRS}:${SHARDE_FUJIMO_HN_PORT_OF} --eval 'db.adminCommand({ ping: 1 })' >/dev/null 2>&1; do sleep 2; done
        mongod --replSet fujimoRS --bind_ip_all --port ${SHARDE_FUJIMO_HN_PORT_OF} --dbpath /data/db/SHARDE_FUJIMO_HN --auth --keyFile /etc/mongo-keyfile --setParameter enableLocalhostAuthBypass=0 --fork --logpath /tmp/SHARDE_FUJIMO_HN/mongod.log --shardsvr
        until mongosh --quiet --host ${SHARDE_FUJIMO_HN_ADRS}:${SHARDE_FUJIMO_HN_PORT_OF} --eval 'db.adminCommand({ ping: 1 })' > /dev/null 2>&1; do sleep 2; done
        echo 'THE SHARDE-FUJIMO-HN HAVE FINISHED BOOTING UP WITH AUTH'

        echo 'WAITING FOR STARTING UP SHARDE-FUJIMO-SG IN PROGRESS WITH AUTH'
        mongod --shutdown --dbpath /data/db/SHARDE_FUJIMO_SG
        until ! mongosh --quiet --host ${SHARDE_FUJIMO_SG_ADRS}:${SHARDE_FUJIMO_SG_PORT_OF} --eval 'db.adminCommand({ ping: 1 })' >/dev/null 2>&1; do sleep 2; done
        mongod --replSet fujimoRS --bind_ip_all --port ${SHARDE_FUJIMO_SG_PORT_OF} --dbpath /data/db/SHARDE_FUJIMO_SG --auth --keyFile /etc/mongo-keyfile --setParameter enableLocalhostAuthBypass=0 --fork --logpath /tmp/SHARDE_FUJIMO_SG/mongod.log --shardsvr
        until mongosh --quiet --host ${SHARDE_FUJIMO_SG_ADRS}:${SHARDE_FUJIMO_SG_PORT_OF} --eval 'db.adminCommand({ ping: 1 })' > /dev/null 2>&1; do sleep 2; done
        echo 'THE SHARDE-FUJIMO-SG HAVE FINISHED BOOTING UP WITH AUTH'
        # ------------------------------------------------------------------------- SHARDE_FUJIMO TAIL

        # ------------------------------------------------------------------------- SHARDE_MATTER HEAD
        mkdir -p /data/db/SHARDE_MATTER_DN
        mkdir -p /data/db/SHARDE_MATTER_HN
        mkdir -p /data/db/SHARDE_MATTER_SG
        mkdir -p /tmp/SHARDE_MATTER_DN
        mkdir -p /tmp/SHARDE_MATTER_HN
        mkdir -p /tmp/SHARDE_MATTER_SG

        echo 'STARTING UP SHARDE-MATTER-DN IN PROGRESS WITH NO AUTH'
        mongod --replSet matterRS --bind_ip_all --port ${SHARDE_MATTER_DN_PORT_OF} --dbpath /data/db/SHARDE_MATTER_DN --fork --logpath /tmp/SHARDE_MATTER_DN/mongod.log --configsvr
        echo 'THE SHARDE-MATTER-DN HAVE FINISHED BOOTING UP WITH NO AUTH'

        echo 'STARTING UP SHARDE-MATTER-HN IN PROGRESS WITH NO AUTH'
        mongod --replSet matterRS --bind_ip_all --port ${SHARDE_MATTER_HN_PORT_OF} --dbpath /data/db/SHARDE_MATTER_HN --fork --logpath /tmp/SHARDE_MATTER_HN/mongod.log --configsvr
        echo 'THE SHARDE-MATTER-HN HAVE FINISHED BOOTING UP WITH NO AUTH'

        echo 'STARTING UP SHARDE-MATTER-SG IN PROGRESS WITH NO AUTH'
        mongod --replSet matterRS --bind_ip_all --port ${SHARDE_MATTER_SG_PORT_OF} --dbpath /data/db/SHARDE_MATTER_SG --fork --logpath /tmp/SHARDE_MATTER_SG/mongod.log --configsvr
        echo 'THE SHARDE-MATTER-SG HAVE FINISHED BOOTING UP WITH NO AUTH'

        echo 'WAITING SHARDE-MATTER-DN FOR INIT'
        mongosh --host ${SHARDE_MATTER_DN_ADRS}:${SHARDE_MATTER_DN_PORT_OF} /init/init-sharde-matter.js
        echo 'SHARDE-MATTER-DN INIT DONE'

        echo 'WAITING FOR STARTING UP SHARDE-MATTER-DN IN PROGRESS WITH AUTH'
        mongod --shutdown --dbpath /data/db/SHARDE_MATTER_DN
        until ! mongosh --quiet --host ${SHARDE_MATTER_DN_ADRS}:${SHARDE_MATTER_DN_PORT_OF} --eval 'db.adminCommand({ ping: 1 })' >/dev/null 2>&1; do sleep 2; done
        mongod --replSet matterRS --bind_ip_all --port ${SHARDE_MATTER_DN_PORT_OF} --dbpath /data/db/SHARDE_MATTER_DN --auth --keyFile /etc/mongo-keyfile --setParameter enableLocalhostAuthBypass=0 --fork --logpath /tmp/SHARDE_MATTER_DN/mongod.log --configsvr
        until mongosh --quiet --host ${SHARDE_MATTER_DN_ADRS}:${SHARDE_MATTER_DN_PORT_OF} --eval 'db.adminCommand({ ping: 1 })' > /dev/null 2>&1; do sleep 2; done
        echo 'THE SHARDE-MATTER-DN HAVE FINISHED BOOTING UP WITH AUTH'

        echo 'WAITING FOR STARTING UP SHARDE-MATTER-HN IN PROGRESS WITH AUTH'
        mongod --shutdown --dbpath /data/db/SHARDE_MATTER_HN
        until ! mongosh --quiet --host ${SHARDE_MATTER_HN_ADRS}:${SHARDE_MATTER_HN_PORT_OF} --eval 'db.adminCommand({ ping: 1 })' >/dev/null 2>&1; do sleep 2; done
        mongod --replSet matterRS --bind_ip_all --port ${SHARDE_MATTER_HN_PORT_OF} --dbpath /data/db/SHARDE_MATTER_HN --auth --keyFile /etc/mongo-keyfile --setParameter enableLocalhostAuthBypass=0 --fork --logpath /tmp/SHARDE_MATTER_HN/mongod.log --configsvr
        until mongosh --quiet --host ${SHARDE_MATTER_HN_ADRS}:${SHARDE_MATTER_HN_PORT_OF} --eval 'db.adminCommand({ ping: 1 })' > /dev/null 2>&1; do sleep 2; done
        echo 'THE SHARDE-MATTER-HN HAVE FINISHED BOOTING UP WITH AUTH'

        echo 'WAITING FOR STARTING UP SHARDE-MATTER-SG IN PROGRESS WITH AUTH'
        mongod --shutdown --dbpath /data/db/SHARDE_MATTER_SG
        until ! mongosh --quiet --host ${SHARDE_MATTER_SG_ADRS}:${SHARDE_MATTER_SG_PORT_OF} --eval 'db.adminCommand({ ping: 1 })' >/dev/null 2>&1; do sleep 2; done
        mongod --replSet matterRS --bind_ip_all --port ${SHARDE_MATTER_SG_PORT_OF} --dbpath /data/db/SHARDE_MATTER_SG --auth --keyFile /etc/mongo-keyfile --setParameter enableLocalhostAuthBypass=0 --fork --logpath /tmp/SHARDE_MATTER_SG/mongod.log --configsvr
        until mongosh --quiet --host ${SHARDE_MATTER_SG_ADRS}:${SHARDE_MATTER_SG_PORT_OF} --eval 'db.adminCommand({ ping: 1 })' > /dev/null 2>&1; do sleep 2; done
        echo 'THE SHARDE-MATTER-SG HAVE FINISHED BOOTING UP WITH AUTH'
        # ------------------------------------------------------------------------- SHARDE_MATTER TAIL

        # ------------------------------------------------------------------------- MONGOS_ROUTER HEAD
        mkdir -p /tmp/MONGOS_ROUTER_DN
        mkdir -p /tmp/MONGOS_ROUTER_HN
        mkdir -p /tmp/MONGOS_ROUTER_SG

        echo 'CONFIGURATING CONFIG SERVER FOR MONGOS-ROUTER-DN'
        mongos --configdb matterRS/${SHARDE_MATTER_DN_ADRS}:${SHARDE_MATTER_DN_PORT_OF},${SHARDE_MATTER_HN_ADRS}:${SHARDE_MATTER_HN_PORT_OF},${SHARDE_MATTER_SG_ADRS}:${SHARDE_MATTER_SG_PORT_OF} --bind_ip_all --port ${MONGOS_ROUTER_DN_PORT_OF} --keyFile /etc/mongo-keyfile --fork --logpath /tmp/MONGOS_ROUTER_DN/mongod.log
        until mongosh --quiet --port ${MONGOS_ROUTER_DN_PORT_OF} -u ${MONGO_ADMINIST_SHARDE_MATTER} -p ${MONGO_PASSWORD_SHARDE_MATTER} --authenticationDatabase admin --eval 'db.adminCommand({ ping: 1 }).ok' | grep 1 > /dev/null; do sleep 2; done
        echo 'CONFIG-SERVER-DN FOR MONGOS-ROUTER-DN CONFIGURATION COMPLETED'

        echo 'WAITING FOR STARTING UP MONGOS-ROUTER-DN IN PROGRESS'
        mongosh --port ${MONGOS_ROUTER_DN_PORT_OF} -u ${MONGO_ADMINIST_SHARDE_MATTER} -p ${MONGO_PASSWORD_SHARDE_MATTER} --authenticationDatabase admin /init/cluster.js
        echo 'THE MONGOS-ROUTER-DN HAVE FINISHED BOOTING UP'

        echo 'CONFIGURATING CONFIG SERVER FOR MONGOS-ROUTER-HN'
        mongos --configdb matterRS/${SHARDE_MATTER_HN_ADRS}:${SHARDE_MATTER_HN_PORT_OF},${SHARDE_MATTER_HN_ADRS}:${SHARDE_MATTER_HN_PORT_OF},${SHARDE_MATTER_SG_ADRS}:${SHARDE_MATTER_SG_PORT_OF} --bind_ip_all --port ${MONGOS_ROUTER_HN_PORT_OF} --keyFile /etc/mongo-keyfile --fork --logpath /tmp/MONGOS_ROUTER_HN/mongod.log
        until mongosh --quiet --port ${MONGOS_ROUTER_HN_PORT_OF} -u ${MONGO_ADMINIST_SHARDE_MATTER} -p ${MONGO_PASSWORD_SHARDE_MATTER} --authenticationDatabase admin --eval 'db.adminCommand({ ping: 1 }).ok' | grep 1 > /dev/null; do sleep 2; done
        echo 'CONFIG-SERVER-HN FOR MONGOS-ROUTER-HN CONFIGURATION COMPLETED'

        echo 'WAITING FOR STARTING UP MONGOS-ROUTER-HN IN PROGRESS'
        mongosh --port ${MONGOS_ROUTER_HN_PORT_OF} -u ${MONGO_ADMINIST_SHARDE_MATTER} -p ${MONGO_PASSWORD_SHARDE_MATTER} --authenticationDatabase admin
        echo 'THE MONGOS-ROUTER-HN HAVE FINISHED BOOTING UP'

        echo 'CONFIGURATING CONFIG SERVER FOR MONGOS-ROUTER-SG'
        mongos --configdb matterRS/${SHARDE_MATTER_SG_ADRS}:${SHARDE_MATTER_SG_PORT_OF},${SHARDE_MATTER_HN_ADRS}:${SHARDE_MATTER_HN_PORT_OF},${SHARDE_MATTER_SG_ADRS}:${SHARDE_MATTER_SG_PORT_OF} --bind_ip_all --port ${MONGOS_ROUTER_SG_PORT_OF} --keyFile /etc/mongo-keyfile --fork --logpath /tmp/MONGOS_ROUTER_SG/mongod.log
        until mongosh --quiet --port ${MONGOS_ROUTER_SG_PORT_OF} -u ${MONGO_ADMINIST_SHARDE_MATTER} -p ${MONGO_PASSWORD_SHARDE_MATTER} --authenticationDatabase admin --eval 'db.adminCommand({ ping: 1 }).ok' | grep 1 > /dev/null; do sleep 2; done
        echo 'CONFIG-SERVER-SG FOR MONGOS-ROUTER-SG CONFIGURATION COMPLETED'

        echo 'WAITING FOR STARTING UP MONGOS-ROUTER-SG IN PROGRESS'
        mongosh --port ${MONGOS_ROUTER_SG_PORT_OF} -u ${MONGO_ADMINIST_SHARDE_MATTER} -p ${MONGO_PASSWORD_SHARDE_MATTER} --authenticationDatabase admin
        echo 'THE MONGOS-ROUTER-SG HAVE FINISHED BOOTING UP'
        # ------------------------------------------------------------------------- MONGOS_ROUTER TAIL

        tail -f /dev/null
      "

  devlop-expres-io:
    container_name: ${APP_NAME}_devlop-expres-io
    image: *mongo-express-image
    env_file: ../../.env
    ports:
      - ${MONGOS_EXPRES_IO_PORT}:${MONGOS_EXPRES_IO_PORT_OF}
    restart: always
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_ADMINIST_SHARDE_MATTER}:${MONGO_PASSWORD_SHARDE_MATTER}@${MONGOS_ROUTER_DN_ADRS}:${MONGOS_ROUTER_DN_PORT_OF},${MONGOS_ROUTER_HN_ADRS}:${MONGOS_ROUTER_HN_PORT_OF},${MONGOS_ROUTER_SG_ADRS}:${MONGOS_ROUTER_SG_PORT_OF}/admin?authSource=admin
      ME_CONFIG_BASICAUTH_USERNAME: ${EXPRESS_ADMINIST}
      ME_CONFIG_BASICAUTH_PASSWORD: ${EXPRESS_PASSWORD}
      PORT: ${MONGOS_EXPRES_IO_PORT_OF}
    command: |
      bash -c "
      echo 'Waiting for mongos startup...'

      until nc -z \"$${MONGOS_ROUTER_DN_ADRS}\" \"$${MONGOS_ROUTER_DN_PORT_OF}\"; do sleep 2; done
      until nc -z \"$${MONGOS_ROUTER_HN_ADRS}\" \"$${MONGOS_ROUTER_HN_PORT_OF}\"; do sleep 2; done
      until nc -z \"$${MONGOS_ROUTER_SG_ADRS}\" \"$${MONGOS_ROUTER_SG_PORT_OF}\"; do sleep 2; done

      echo 'mongos is ready'

      exec node app
      "
    networks:
      - master-netwrk

volumes:
  devlop-router-ms-da:
  devlop-router-ms-cf:
