name: mongos-router-hn

networks:
  master-netwrk:
    external: true

services:
  mongos-router-hn:
    container_name: ${APP_NAME}_mongos-router-hn
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./keyfile:/etc
      - mongos-router-hn-da:/data/db
      - mongos-router-hn-cf:/data/configdb
    env_file: ../../.env
    ports:
      - ${MONGOS_ROUTER_HN_PORT}:${MONGOS_ROUTER_HN_PORT_OF}
    networks:
      - master-netwrk

volumes:
  mongos-router-hn-da:
  mongos-router-hn-cf:
