name: mongos-router-dn

networks:
  master-netwrk:
    external: true

services:
  mongos-router-dn:
    container_name: ${APP_NAME}_mongos-router-dn
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./keyfile:/etc
      - mongos-router-dn-da:/data/db
      - mongos-router-dn-cf:/data/configdb
      - ./init/cluster.js:/init/cluster.js:ro
    env_file: ../../.env
    ports:
      - ${MONGOS_ROUTER_DN_PORT}:${MONGOS_ROUTER_DN_PORT_OF}
    networks:
      - master-netwrk

volumes:
  mongos-router-dn-da:
  mongos-router-dn-cf:
