name: mongos-router-dn

x-mongo-image: &mongo-image mongo:7.0.14@sha256:0032d2ca20db5fa34926f196c8a43b74e34ed239a7f2453ff1505b6f12ba8ea6

networks:
  master-netwrk:
    external: true

services:
  mongos-router-dn:
    container_name: ${APP_NAME}_mongos-router-dn
    image: *mongo-image
    volumes:
      - ./keyfile:/etc
      - mongos-router-dn-da:/data/db
      - mongos-router-dn-cf:/data/configdb
      - ./init/cluster.js:/init/cluster.js:ro
    env_file: ../../.env
    ports:
      - ${MONGOS_ROUTER_DN_PORT}:${MONGOS_ROUTER_DN_PORT_OF}
    networks:
      - master-netwrk
    command: |
      bash -c "
        set -e

        echo 'WAITING FOR KEYFILE...'
        while [ ! -f /etc/mongo-keyfile ]; do sleep 2; done
        echo 'KEYFILE CREATED'

        echo 'WAITING FOR STARTING UP SHARDE-MATTER-SG IN PROGRESS WITH AUTH'
        until mongosh --quiet --host ${SHARDE_MATTER_SG_ADRS}:${SHARDE_MATTER_SG_PORT_OF} -u ${MONGO_ADMINIST_SHARDE_MATTER} -p ${MONGO_PASSWORD_SHARDE_MATTER} --authenticationDatabase admin --eval 'db.adminCommand({ ping: 1 })' > /dev/null 2>&1; do sleep 2; done
        echo 'THE SHARDE-MATTER-SG HAVE FINISHED BOOTING UP WITH AUTH'

        echo 'CONFIGURATING CONFIG SERVER FOR MONGOS-ROUTER-DN'
        mongos --configdb matterRS/${SHARDE_MATTER_DN_ADRS}:${SHARDE_MATTER_DN_PORT_OF},${SHARDE_MATTER_HN_ADRS}:${SHARDE_MATTER_HN_PORT_OF},${SHARDE_MATTER_SG_ADRS}:${SHARDE_MATTER_SG_PORT_OF} --bind_ip_all --port ${MONGOS_ROUTER_DN_PORT_OF} --keyFile /etc/mongo-keyfile --fork --logpath /tmp/mongod.log
        until mongosh --quiet --port ${MONGOS_ROUTER_DN_PORT_OF} -u ${MONGO_ADMINIST_SHARDE_MATTER} -p ${MONGO_PASSWORD_SHARDE_MATTER} --authenticationDatabase admin --eval 'db.adminCommand({ ping: 1 }).ok' | grep 1 > /dev/null; do sleep 2; done
        echo 'CONFIG-SERVER-DN FOR MONGOS-ROUTER-DN CONFIGURATION COMPLETED'

        echo 'WAITING FOR STARTING UP SHARDE-EVERES-SG IN PROGRESS WITH AUTH'
        until mongosh --quiet --host ${SHARDE_EVERES_SG_ADRS}:${SHARDE_EVERES_SG_PORT_OF} -u ${MONGO_ADMINIST_SHARDE_EVERES} -p ${MONGO_PASSWORD_SHARDE_EVERES} --authenticationDatabase admin --eval 'db.adminCommand({ ping: 1 })' > /dev/null 2>&1; do sleep 2; done
        echo 'THE SHARDE-EVERES-SG HAVE FINISHED BOOTING UP WITH AUTH'

        echo 'WAITING FOR STARTING UP SHARDE-FANSIP-SG IN PROGRESS WITH AUTH'
        until mongosh --quiet --host ${SHARDE_FANSIP_SG_ADRS}:${SHARDE_FANSIP_SG_PORT_OF} -u ${MONGO_ADMINIST_SHARDE_FANSIP} -p ${MONGO_PASSWORD_SHARDE_FANSIP} --authenticationDatabase admin --eval 'db.adminCommand({ ping: 1 })' > /dev/null 2>&1; do sleep 2; done
        echo 'THE SHARDE-FANSIP-SG HAVE FINISHED BOOTING UP WITH AUTH'

        echo 'WAITING FOR STARTING UP SHARDE-FUJIMO-SG IN PROGRESS WITH AUTH'
        until mongosh --quiet --host ${SHARDE_FUJIMO_SG_ADRS}:${SHARDE_FUJIMO_SG_PORT_OF} -u ${MONGO_ADMINIST_SHARDE_FUJIMO} -p ${MONGO_PASSWORD_SHARDE_FUJIMO} --authenticationDatabase admin --eval 'db.adminCommand({ ping: 1 })' > /dev/null 2>&1; do sleep 2; done
        echo 'THE SHARDE-FUJIMO-SG HAVE FINISHED BOOTING UP WITH AUTH'

        echo 'WAITING FOR STARTING UP MONGOS-ROUTER-DN IN PROGRESS'
        mongosh --port ${MONGOS_ROUTER_DN_PORT_OF} -u ${MONGO_ADMINIST_SHARDE_MATTER} -p ${MONGO_PASSWORD_SHARDE_MATTER} --authenticationDatabase admin /init/cluster.js
        echo 'THE MONGOS-ROUTER-DN HAVE FINISHED BOOTING UP'

        tail -f /tmp/mongod.log
      "

volumes:
  mongos-router-dn-da:
  mongos-router-dn-cf:
