name: sharde-fujimo-hn

networks:
  master-netwrk:
    external: true

services:
  sharde-fujimo-hn:
    container_name: ${APP_NAME}_sharde-fujimo-hn
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./keyfile:/etc
      - sharde-fujimo-hn-da:/data/db
      - sharde-fujimo-hn-cf:/data/configdb
    env_file: ../../.env
    ports:
      - ${SHARDE_FUJIMO_HN_PORT}:${SHARDE_FUJIMO_HN_PORT_OF}
    networks:
      - master-netwrk

volumes:
  sharde-fujimo-hn-da:
  sharde-fujimo-hn-cf:
