name: wizard-sharde-fujimo-sg

networks:
  master-netwrk:
    external: true

services:
  wizard-sharde-fujimo-sg:
    container_name: ${APP_NAME}_sharde-fujimo-sg
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./keyfile:/etc
      - wizard-sharde-fujimo-sg-da:/data/db
      - wizard-sharde-fujimo-sg-cf:/data/configdb
    env_file: ../../.env
    ports:
      - ${SHARDE_FUJIMO_SG_PORT}:${SHARDE_FUJIMO_SG_PORT_OF}
    networks:
      - master-netwrk

volumes:
  wizard-sharde-fujimo-sg-da:
  wizard-sharde-fujimo-sg-cf:
