name: sharde-fansip-sg

networks:
  master-netwrk:
    external: true

services:
  sharde-fansip-sg:
    container_name: ${APP_NAME}_sharde-fansip-sg
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./keyfile:/etc
      - sharde-fansip-sg-da:/data/db
      - sharde-fansip-sg-cf:/data/configdb
    env_file: ../../.env
    ports:
      - ${SHARDE_FANSIP_SG_PORT}:${SHARDE_FANSIP_SG_PORT_OF}
    networks:
      - master-netwrk

volumes:
  sharde-fansip-sg-da:
  sharde-fansip-sg-cf:
