name: wizard-sharde-matter-dn

networks:
  master-netwrk:
    external: true

services:
  wizard-sharde-matter-dn:
    container_name: ${APP_NAME}_sharde-matter-dn
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./keyfile:/etc
      - wizard-sharde-matter-dn-da:/data/db
      - wizard-sharde-matter-dn-cf:/data/configdb
      - ./init/init-sharde-matter.js:/init/init-sharde-matter.js:ro
    env_file: ../../.env
    ports:
      - ${SHARDE_MATTER_DN_PORT}:${SHARDE_MATTER_DN_PORT_OF}
    networks:
      - master-netwrk

volumes:
  wizard-sharde-matter-dn-da:
  wizard-sharde-matter-dn-cf:
