name: keygen-suicid-cr

networks:
  master-netwrk:
    external: true

services:
  keygen-suicid-cr:
    container_name: ${APP_NAME}_keygen-suicid-cr
    build: .
    volumes:
      - ./keyfile:/keyfile
      - ./create-keyfile.sh:/create-keyfile.sh
      - /var/run/docker.sock:/var/run/docker.sock
    entrypoint: ["bash", "/create-keyfile.sh"]
    networks:
      - master-netwrk
