name: sharde-matter-hn

networks:
  master-netwrk:
    external: true

services:
  sharde-matter-hn:
    container_name: ${APP_NAME}_sharde-matter-hn
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./keyfile:/etc
      - sharde-matter-hn-da:/data/db
      - sharde-matter-hn-cf:/data/configdb
    env_file: ../../.env
    ports:
      - ${SHARDE_MATTER_HN_PORT}:${SHARDE_MATTER_HN_PORT_OF}
    networks:
      - master-netwrk

volumes:
  sharde-matter-hn-da:
  sharde-matter-hn-cf:
