name: wizard-sharde-everes-sg

networks:
  master-netwrk:
    external: true

services:
  wizard-sharde-everes-sg:
    container_name: ${APP_NAME}_sharde-everes-sg
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./keyfile:/etc
      - wizard-sharde-everes-sg-da:/data/db
      - wizard-sharde-everes-sg-cf:/data/configdb
    env_file: ../../.env
    ports:
      - ${SHARDE_EVERES_SG_PORT}:${SHARDE_EVERES_SG_PORT_OF}
    networks:
      - master-netwrk

volumes:
  wizard-sharde-everes-sg-da:
  wizard-sharde-everes-sg-cf:
