name: wizard-sharde-fansip-hn

networks:
  master-netwrk:
    external: true

services:
  wizard-sharde-fansip-hn:
    container_name: ${APP_NAME}_sharde-fansip-hn
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./keyfile:/etc
      - wizard-sharde-fansip-hn-da:/data/db
      - wizard-sharde-fansip-hn-cf:/data/configdb
    env_file: ../../.env
    ports:
      - ${SHARDE_FANSIP_HN_PORT}:${SHARDE_FANSIP_HN_PORT_OF}
    networks:
      - master-netwrk

volumes:
  wizard-sharde-fansip-hn-da:
  wizard-sharde-fansip-hn-cf:
