name: wizard-sharde-fansip-dn

networks:
  master-netwrk:
    external: true

services:
  wizard-sharde-fansip-dn:
    container_name: ${APP_NAME}_sharde-fansip-dn
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./keyfile:/etc
      - wizard-sharde-fansip-dn-da:/data/db
      - wizard-sharde-fansip-dn-cf:/data/configdb
      - ./init/init-sharde-fansip.js:/init/init-sharde-fansip.js:ro
    env_file: ../../.env
    ports:
      - ${SHARDE_FANSIP_DN_PORT}:${SHARDE_FANSIP_DN_PORT_OF}
    networks:
      - master-netwrk

volumes:
  wizard-sharde-fansip-dn-da:
  wizard-sharde-fansip-dn-cf:
